version: "3.8"

services:
  jenkins:
    container_name: jenkins
    image: 'eu-jenkins'
    build:
      context: ./docker/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "./docker/jenkins/data:/var/jenkins_home"
    extra_hosts:
      - "host.docker.internal:host-gateway"